### ISSUE TITLE
Please, provide a COMPLETE example of how to use this.

### ISSUE THREAD

**Issue by sabsaxo** [fresheneesz/requireTraverser#3]
With absolute paths etc. I'm guessing wildly wrong trying to get anything out of this ...

**Comment by sabsaxo** [comment]
OK, had to give up on this, as it made absolutely no sense.

**Comment by fresheneesz** [comment]
@sabsaxo Can you post your most recent attempt? The module is fully documented. The example I have in the readme is for calling 

```
var rt = require('require-traverser')
rt('.', 'fileName.js', function(e, results) {
   console.dir(results)
})
```

The test folder also has a number of examples you can take a look at. If you'd like me to help you figure out  your specific issue, post some code.

**Comment by sabsaxo** [comment]
Well, it just proved my point: why don't I see anything like that in the README? Would have made it WAY more clear to understand the syntax. Went for another solution all together though. If you want people to have a good experience using your projects, then you should make it E X T R E M E L Y easy to understand; don't assume anything.

And please, add the above code snippet to the README, as I'm sure it will help others in the future ; ).

**Comment by fresheneesz** [comment]
> Well, it just proved my point: why don't I see anything like that in the README?

I make sure that my modules are fully documented and easy to understand. I also have full tests for most of my modules. You're right that a full example makes it easier, but give me some credit.. Understand that open source projects are a community effort. 

Anyways, I added it.

**Comment by sabsaxo** [comment]
Here you go: CREDIT * 4

; )

Thanks.

**Comment by fresheneesz** [comment]
A star would be nice : )
